# configs/your_action_config.yaml

# ===== 数据集设置 =====
dataset:
  train_dir: data/train
  val_dir:   data/val
  test_dir:  data/test

  # 类别映射
  label_map:
    Align_screwdriver:     0
    Approach:              1
    Idle:                  2
    No_human:              3
    Pick_bolt:             4
    Pick_cover:            5
    Pick_screwdriver:      6
    Place_bolt:            7
    Place_cover:           8
    Put_down_screwdriver:  9
    Screw:                10
    Transition:           11

  window_size: 9     # 定长帧数
  stride:      3      # 滑动步长
  enable_transform: true  # 是否启用数据增强

# ===== DataLoader 参数 =====
train:
  batch_size:   32
  num_workers:  4     # 4个子进程加载训练数据
  shuffle:      true

val:
  batch_size:   32
  num_workers:  4     
  shuffle:      false

test:
  batch_size:   16
  num_workers:  4    
  shuffle:      false

# ===== ViT模型配置 =====
model:
  backbone:
    img_size:    384 # 384 512
    patch_size:  128
    in_chans:   4
    num_classes: 12
    embed_dim:   768
    depth:      12
    num_heads:  12
    mlp_ratio:  4.
    qkv_bias:   true
    qk_scale:   null
    drop_rate:  0.
    attn_drop_rate: 0.
    drop_path_rate: 0.3
    hybrid_backbone: null
    norm_layer:  null
    use_checkpoint: false
    frozen_stages: -1
    ratio:       1
    last_norm:  true
    patch_padding: pad
    freeze_attn: false
    freeze_ffn:  false

  neck:
    input_dim:  768
    hidden_dim: 256
    mode: mean           # 可选：lstm / mean / none

  head:
    input_dim:    256  # 与 neck 输出一致
    num_classes:  12
    dropout_prob: 0.5

# ===== cnn模型配置 =====
cnn_model:
  input_dim:  4          # 输入通道数
  output_dim: 12          # 输出类别数
  input_height: 128          # 输入图像高度
  input_width: 128           # 输入图像宽度


# ===== 优化器 & 训练 =====
optimizer:
  type:         Adam
  lr:           0.0001
  weight_decay: 1e-3

epochs:   30
device:   cuda:0
work_dir: results/checkpoints
log_dir: results/logs
